package com.example.Network.Protocol;

public enum MessageType {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    CREATE_PRIVATE_GAME,
    CREATE_PRIVATE_GAME_SUCCESS,
    CREATE_PRIVATE_GAME_FAILED,
    JOIN_PRIVATE_GAME,
    JOIN_PRIVATE_GAME_SUCCESS,
    JOIN_PRIVATE_GAME_FAILED,
    START_PUBLIC_GAME,
    START_PUBLIC_GAME_SUCCESS,
    START_PUBLIC_GAME_FAILED,

    // In Game protocol
    READY,
    SUBMIT,
    CHALLENGE,
    SKIP,
    RESIGN,
    SWAP,

    TILEBAG,

    GAME_START,
    PLAYER_HAVE_PLAYED,
    PLAYER_IS_READY,
    PLAYER_TURN,
    PLAYER_SCORE,
    WINNER
}
